### ISSUE TITLE
Document syntax in the manual

### ISSUE THREAD

**Issue by Gbury** [Deducteam/Dedukti#102]
Whenever a user wants to output dedukti, it would be particularly useful to have access to the official description of the syntax in the manual (or really hosted anywhere with a minimum of documentation).

For instance, how is one supposed to know the lexical/syntactic restrictions on identifiers ? (are Unicode character allowed ? are they normalized ? can an identifier start with an uppercase letter (ASCII or Unicode ?), with a number ? a non-ascii character ? etc...).

**Comment by francoisthire** [comment]
@Gbury If you are still interesting to this, I suppose you should look at https://github.com/Deducteam/lambdapi now. I close the issue.
