### ISSUE TITLE
Type checking a rewrite rule under constraints

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#104]
An example of a rewrite system rejected by Dedukti, but that could be accepted if it did not throw some constraints:

```
A : Type.

def f : A -> A.

def a : A -> A.

def b : A -> A.

[x] f (b x) --> f (a x).


B : A -> Type.

def g : x:A -> B (a x) -> B (b x) -> B (f (a x)) -> B (f (a x)).

[x,ba,y] g x ba ba  ba --> ba.
```

By the way, this system is accepted by `lambdapi`.

**Comment by fblanqui** [comment]
Well, constraints seem useless in this example. The LHS has type B(f(a 
x)) and the RHS has type the type of ba which is B(f(a x)) too as it is 
the 3rd argument of g.


Le 21/08/2018 à 17:29, fthire a écrit :

**Comment by rafoo** [comment]
What is the issue? Do you think that this file should be accepted by Dedukti or that it should be rejected by lambdapi?

**Comment by francoisthire** [comment]
When the left-hand side is well-typed, the righ hand side is also
well-typed in this example. I think the correct behavior then is to accept
this rule.

**Comment by francoisthire** [comment]
See issue #72 for an other example.
