### ISSUE TITLE
Follow the GNU/POSIX guidelines for the command-line options

### ISSUE THREAD

**Issue by Gbury** [Deducteam/Dedukti#111]
Options using more than 1 char should be preceded by 2 dashes, for instance `--version` and not `-version`. As far as I can tell, the rationale behind that is that `foo -abc` should be equivalent to `foo -a -b -c` according to the [POSIX guidelines](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)).

Cmdliner could help a lot with that (and also with generating manpages, cf #100 ).

**Comment by Gbury** [comment]
While I'm at it, listing options in alphabetical order in the `--help` output would be nice.

**Comment by rafoo** [comment]
I am not sure that following these guidelines is common in the community. For example, both Ocaml and Coq use a single dash in front of long options and they do not sort the options alphabetically in the output of `-help`.

**Comment by Gbury** [comment]
At least in the case of ocaml, this is because the first versions of ocaml predate these guidelines. And I believe Coq suffers from using the Arg module (at least in the beginning), which doesn't engage the guidelines (again, probably because it predates the guidelines). All of this shouldn't be reason enough to not follow the guidelines in dedukti in my opinion.

**Comment by fblanqui** [comment]
I agree. And it's easy to do.


Le 04/09/2018 à 11:51, Guillaume Bury a écrit :

**Comment by francoisthire** [comment]
@Gaspi  #116 ?

**Comment by francoisthire** [comment]
Good idea but wont be fixed.

**Comment by rafoo** [comment]
Isn't this fixed by https://github.com/Deducteam/Dedukti/pull/159 ?
-- 
Raphaël Cauderlier

**Comment by francoisthire** [comment]
I thought we did it only for some options, but maybe not after all.
