### ISSUE TITLE
Is HNF useful?

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#113]
There are three different normal forms implemented in Dedukti:

- SNF
- HNF
- WHNF (that is not well-defined yet)

But I have the impression that HNF is never used. Then, is it useful to keep it?

**Comment by fblanqui** [comment]
I would prefer to keep HNF. Indeed, what's the point of WHNF for a user?


Le 04/09/2018 à 10:48, fthire a écrit :

**Comment by rafoo** [comment]
As a user I do not remember the last time I used a normalisation command other than #SNF and #STEP.

**Comment by francoisthire** [comment]
> I would prefer to keep HNF. Indeed, what's the point of WHNF for a user?

For debugging purposes, it is preferable to use WHNF instead of HNF.

**Comment by fblanqui** [comment]
Why?


Le 04/09/2018 à 13:30, fthire a écrit :

**Comment by francoisthire** [comment]
Because you can trace the behavior of Dedukti since it uses WHNF instead of HNF. Otherwise, I think you want to compute the SNF.

**Comment by GuillaumeGen** [comment]
Because it allows the user to follow the computations made during type-checking, and type-checking uses (mostly, see @Gaspi for details) WHNF when it has to reduce.

**Comment by fblanqui** [comment]
Right. Just remark that the output of WHNF on an abstraction is itself.


Le 04/09/2018 à 13:43, GuillaumeGen a écrit :
