### ISSUE TITLE
Dkmeta in Dedukti

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#115]
Dkmeta is a tool that mainly aims to use the rewrite engine of Dedukti as a programming language. 

Dkmeta offers two features:

### Normalization

`dkmeta --meta foo.dk bar.dk`

will normalize the file `bar.dk` according to the rules declared in `foo.dk` (and only this rules). This way. you can implement tactics for Dedukti (see [dktactics](https://gitlab.math.univ-paris-diderot.fr/cauderlier/dktactics)). 

### Quote/Unquote 

However, sometimes you really want to rewrite Dedukti terms itself. To do that, `dkmeta` offers also a quote/unquote mechanism. This allows you to write rewrite rules with a product on the LHS such as

```
[A,B] quote(eta A -> eta B) --> eta (arrow A B)
```

Using the rewrite rule above, you can rewrite the term

```
(eta nat -> eta nat) -> eta nat
```

as

``` 
eta (arrow (arrow nat nat) nat)
```

Both features combined, makes `dkmeta` another way to implement a small refiner for Dedukti with:
- Tactics
- Implicit parameters
- Better error messages
- Debug information (almost) for free such as computation traces

But also makes things easier when you want to write proof transformations between several logics (especially when some matching is involved).

Right now, a version of [dkmeta](https://github.com/francoisthire/dkmeta) is maintained by me on my own repo. However, following a discussion with @rlepigre , I am wondering whether merging `dkmeta` as a new tool for the "Dedukti suite" would be a good idea.

Since `dkmeta` is already using Dedukti as a library, this would not impact the kernel. Instead, this would add a new file in the `commands` directory, and probably a new folder called `meta` that implements the features above such as the `quote/unquote` mechanism.

**Comment by francoisthire** [comment]
@Gaspi @GuillaumeGen 
dkmeta is here : https://github.com/francoisthire/dkmeta

Btw, should it be on Deducteam repo?

**Comment by fblanqui** [comment]
Yes.

Le 17/05/2019 à 13:39, fthire a écrit :

**Comment by francoisthire** [comment]
Do you agree @Gaspi @gabrielhdt @GuillaumeGen ?

**Comment by francoisthire** [comment]
Probably will be.
