### ISSUE TITLE
Moving to Opam 2.0.0

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/Dedukti#129]
[NOTE] Repository at
       git+https://gforge.inria.fr/git/opam-deducteam/opam-deducteam.git
       doesn't define its version, assuming it's 1.2.

[WARNING] The repository 'deducteam' at
          git+https://gforge.inria.fr/git/opam-deducteam/opam-deducteam.git
          doesn't have a 'repo' file, and might not be compatible with this
          version of opam.

**Comment by GuillaumeGen** [comment]
I thought that the opam-deducteam repo on gforge was outdated.

**Comment by fblanqui** [comment]
No, not completely. There is a number of software that are available only through this repo.

To convert the repo to 2.0, see https://opam.ocaml.org/blog/opam-2-0-0-repo-upgrade-roadmap/#Advice-for-custom-repository-maintainers.

    The opam admin upgrade command can be used to upgrade your repository to 2.0.0 format. We recommand using it, as otherwise clients using opam 2.0.0 will do the upgrade locally every time. Add the option --mirror to continue serving both versions, with automatic redirects.
