### ISSUE TITLE
Problem with Opam

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/Dedukti#142]
When doing an opam update and upgrade, I get the following warning:

⊘ removed   dedukti.2.6.0
[WARNING] package uninstall script failed at
          /home/blanqui/.opam/opam-init/hooks/sandbox.sh remove make uninstall:
          # context     2.0.0 | linux/x86_64 | base-bigarray.base
          base-threads.base base-unix.base ocaml-base-compiler.4.07.0 |
          https://opam.ocaml.org#9bea3748
          # path        ~/.opam/4.07.0/.opam-switch/remove/lambdapi.1.0
          # command     ~/.opam/opam-init/hooks/sandbox.sh remove make
          uninstall
          # exit-code   2
          # env-file    ~/.opam/log/lambdapi-7760-27656f.env
          # output-file ~/.opam/log/lambdapi-7760-27656f.out
          ### output ###
          # Removed /home/blanqui/.opam/4.07.0/lib/lambdapi/META
          # ocamlfind: /home/blanqui/.opam/4.07.0/lib/lambdapi/core: Is a
          directory
          # GNUmakefile:202: recipe for target 'uninstall' failed
          # make: *** [uninstall] Error 2

**Comment by GuillaumeGen** [comment]
If I understand well, this issue is on the wrong repo.
It seems that Dedukti was successfully removed, but lambdapi's uninstall script failed.

**Comment by fblanqui** [comment]
Right.
