### ISSUE TITLE
Relaxing bracket type checking criteria

### ISSUE THREAD

**Issue by Gaspi** [Deducteam/Dedukti#151]
We should relax the criteria to type check brackets.

Right now the criteria is:
- Brackets expression may not contain variables occuring later on.
This is enforced by the "on the fly" typing of the bracket expression in a partial context that do not contain these variables yet.

It should be:
- The inferred type of brackets expressions may (still) not depend on "regular" variables occuring later on. This is because the inferred type for bracket variables doesn't.
- Brackets expression may depend on regular variables occuring later on provided these variables type do not depend themselves on the brackets variable (no circularity).
- Said differently: a regular variable V occuring after some brackets may only have a type depending on bracket variables whose corresponding expression do not contain V itself.

This could be enforced by:
- keeping track of the bracket variables occuring in regular variables inferred that (in normal form or not ?)
- keeping track of the regular variables occuring in previous bracket expressions
- postponing the checking of bracket expressions until after the type checking of the rule.
- performing this typecheking in the final context which has then been built. This allows brackets expression to contain variables introduced afterwards. 
- check for circularity by inspecting the variables occuring in brackets expressions

We typically want to accept things like:
```
[L] max {length L} L --> ...
[x,P] match_eq P {x} {x} (refl x) --> P x.
```

It would also be nice to
- have a flag disabling runtime bracket checks
- detect brackets that are not necessary for the typing of the rule and remove the runtime check for them (especially useful for automatically generated brackets).

The second point is actually debatable since people might rely on / expect the runtime check (for some reason). I usually consider brackets to be a feature allowing the typing of more rules (and the runtime checks to be a necessary nuisance) but maybe some use cases rely on the checks themselves. I guess it's best to warn the user whenever a bracket is not necessary for the typing of the rule (or have flags to handle these cases : keep runtime check / remove check / warn me)

Comment:
This is a required development for the encoding of inductive destruction in Coqine.

**Comment by Gaspi** [comment]
As further justification of the importance of this issue, assume the following (not too far fetched) inductive definition in Coq:
```
Inductive is_pair : nat -> Prop := double : forall n : nat, is_pair (2 * n).
```
A natural translation to Dedukti would be the following:
```
is_pair : Term set nat -> Univ prop.

double : n : Term set nat -> Term prop (is__pair (mul (S (S 0)) n)).

def match_is_pair :
  s : Sort ->
  P : (n : Term set nat -> Term prop (is_pair n) -> Univ s) ->
  case_double : (n : Term set nat ->  Term s (P (mul (S (S 0)) n) (double n))) ->
  n : Term set nat ->
  x : Term prop (is_pair n) ->
  Coq.Term s (P n x).

[ s, P, case_double, n]
  match_is_pair s P case_double {mul (S (S 0)) n} (double n) --> case_double n.
```
In the rewrite rule associated to the inductive destructor elimination (last two lines), the fourth argument of the match operator is a bracket. We can't use the actual expected expression `mul (S (S O)) n` as a pattern at this position because it is headed with a defined operator, `mul` so the pattern would never match any expression and the rule would never fire. It also can't simply be replaced by a fresh variable because the rule would then become ill-typed. The bracket convertibility condition is necessary for the type-checking.

This rule is currently rejected by Dedukti because the bracket expression refers to the variable `n` occuring for the first time after the brackets. However, in that case, it seems safe to allow it since the type of `n` (`Term set nat`) does not depend on bracket's variable.

References:
- [Mathieu Boespflug and Guillaume Burel. _CoqInE: Translating the Calculus of Inductive Constructions into the lambda Pi-calculus Modulo_](http://web4.ensiie.fr/~guillaume.burel/download/boespflug12coqine.pdf) In particular the last few lines.

**Comment by GuillaumeGen** [comment]
Gaspard,

I don't see why we could not replace this bracket with a variable. Does it break subject réduction? Why is your example fundamentally different of `tail m (cons x n l)` where typability of the lhs implies `m = s n` (and no brackets are required)?

Guillaume

**Comment by francoisthire** [comment]
I approve @GuillaumeGen , here is a standalone file:

```dedukti
Sort : Type.

set : Sort.
prop : Sort.

Univ : Sort -> Type.

Term : s : Sort -> Univ s -> Type.

nat : Univ set.

0 : Term set nat.

S : Term set nat -> Term set nat.

mul : Term set nat -> Term set nat -> Term set nat.

is_pair : Term set nat -> Univ prop.

double : n : Term set nat -> Term prop (is_pair (mul (S (S 0)) n)).

def match_is_pair :
  s : Sort ->
  P : (n : Term set nat -> Term prop (is_pair n) -> Univ s) ->
  case_double : (n : Term set nat ->  Term s (P (mul (S (S 0)) n) (double n))) ->
  n : Term set nat ->
  x : Term prop (is_pair n) ->
  Term s (P n x).

(; Need more flexibility for brackets ;)
(;
[ s, P, case_double, n]
  match_is_pair s P case_double {mul (S (S 0)) n} (double n) --> case_double n.
;)

[ s, P, case_double, n]
  match_is_pair s P case_double _ (double n) --> case_double n.
```

**Comment by Gaspi** [comment]
Term is injective in your example while it is not in the encoding, that's the reason it's working here. Replace its declaration with `def Term` and I think it won't typecheck anymore and you would then need the bracket.

**Comment by fblanqui** [comment]
Hello Gaspard. You didn't answer Guillaume's question: does it break SR to replace your bracket by _? A priori, we should clearly separate rule declarations from the problem of checking SR. It may well be possible that, for some user declared rules, the implemented algorithm is unable to check SR. Then, indeed, adding some annotations like brackets could be a way to help such an algorithm. But we may also try to develop more clever algorithms. @wujuihsuan2016 is going to work on this topic in Lambdapi soon. If this is a problem for you to make progress in your developments, I understand your request. An alternative would be to disable SR verification too. Anyway, I invite you to use https://github.com/Deducteam/lambdapi instead.

**Comment by Gaspi** [comment]
Yes, when `Term` is a defined symbol (as in CTS encoding systems), replacing the bracket by _ does break SR in Guillaume's example. The rule becomes ill-typed.

I thought lambdapi didn't have brackets, that's why I posted this issue here. Are there brackets (or an equivalent feature) in lambdapi ?

I'm not sure that this could be fixed by improving the rule type checking algorithm alone. Essentially, here, the type checker who have to infer that `Term` is injective in its second argument.
This issue may rather be fixed by using declared `injectivity` of defined symbol. I'm not sure about the details of this feature in lambdapi. Is it safe to use ? Should there be strong "meta" arguments to ensure injectivity or does lambdapi check it ?

Also, to be more precise, in this example, we need injectivity of `Term` in its second argument:
- When `Term s a ~ Term s b` then `a ~  b` (for all `s`)
- When `Term s a ~ Term t b` we can't deduce anything

**Comment by GuillaumeGen** [comment]
Do you have a witness that SR is broken (ie a typable term whose reduct does not have the same type or is untypable)?

**Comment by Gaspi** [comment]
My bad, I don't think SR is broken. Rules with brackets have the exact same behavior as if their bracket were unapplied fresh variables so obviously replacing the bracket with `_` doesn't change anything. However the rule itself can be typechecked with the bracket while it fails to typecheck when it is replaced with a `_`.

**Comment by fblanqui** [comment]
The point is that the *current* implementation fails to check SR 
(without brackets) but it doesn't mean that SR is broken indeed.

**Comment by fblanqui** [comment]
Le 19/02/2019 à 03:37, Gaspard Férey a écrit :
>
> Yes, when |Term| is a defined symbol (as in CTS encoding systems), 
> replacing the bracket by _ does break SR in Guillaume's example. The 
> rule becomes ill-typed.
>
It doesn't break SR; it's just that the *current* algo is unable to 
check SR.


> I thought lambdapi didn't have brackets, that's why I posted this 
> issue here. Are there brackets (or an equivalent feature) in lambdapi ?
>
Lambdapi has no bracket.


> I'm not sure that this could be fixed by improving the rule type 
> checking algorithm alone. Essentially, here, the type checker who have 
> to infer that |Term| is injective in its second argument.
> This issue may rather be fixed by using declared |injectivity| of 
> defined symbol. I'm not sure about the details of this feature in 
> lambdapi. Is it safe to use ? Should there be strong "meta" arguments 
> to ensure injectivity or does lambdapi check it ?
>
Similarly to confluence and termination, Lambdapi and Dedukti do not 
check injectivity. https://github.com/wujuihsuan2016 will develop an 
algo for this.

**Comment by Gaspi** [comment]
So my conclusion on this would be that Coqine is unable to completely move over from Dedukti to Lambdapi as long as the latter doesn't support one of the following feature:
- powerful enough brackets or similar
- typechecking hints
- (complex) injectivity detection
- injectivity declaration

**Comment by fblanqui** [comment]
I would not be so radical. The most important for you is to have a paper 
proof of SR. Then, in Lambdapi, we can simply make SR checking optional. 
So, there is no reason for not using Lambdapi.

**Comment by Gaspi** [comment]
By "SR checking" you mean "Well Typedness of rules checking", right ? Is it possible to add only a couple of unchecked rules or do I need to disable rule type checking altogether ? If type preservation of rules checking is disabled then what does Lambdapi check exactly besides syntax correctness ? (Or to put it differently : "what is the meaning of success ?")

If I can disable checking for the rules of inductive translation (and rely on manual paper proof) then it would work for me I guess but a bit disappointing since my rules are quite close to being typecheckable.

**Comment by fblanqui** [comment]
Le 19/02/2019 à 16:09, Gaspard Férey a écrit :
>
> By "SR checking" you mean "Well Typedness of rules checking", right ?
>
I mean: a rule l -> r satisfies SR if, for all \Gamma, for all T, for 
all substitutions \sigma, \Gamma |- l\sigma : T implies \Gamma |- 
r\sigma : T.


> Is it possible to add only a couple of unchecked rules or do I need to 
> disable rule type checking altogether ?
>
I suggest to do that indeed, for instance by prefixing a rule 
declaration by "admit sr" (or "admit type preservation")


> If type preservation of rules checking is disabled then what does 
> Lambdapi check exactly besides syntax correctness ? (Or to put it 
> differently : "what is the meaning of success ?")
>
Lambdapi is a proof assistant. In particular, Lambdapi handles 
incomplete proofs/terms using metavariables, and provides tactics to 
instantiate them. In Dedukti, proof checking was done using a kind of 
hack: by using SR. You can still do this in Lambdapi of course but this 
is not the usual way of doing a proof.


> If I can disable checking for the rules of inductive translation (and 
> rely on manual paper proof) then it would work for me I guess but a 
> bit disappointing since my rules are quite close to being typecheckable.
>
>
You can also rely on the work of other people to do that, and get more 
time to focus on your own work. ;-)
