### ISSUE TITLE
Dedukti tutorial: #NAME command

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Dedukti#162]
Trying to follow the Dedukti tutorial (https://deducteam.github.io/tutorial.html), after installing from the current GH master head

The tutorial mentions that 

> A Dedukti file should always start with a line of the form #NAME <module_name>. where <module_name> is the name of the module beeing defined by the file.

But running `dkcheck` on the file, I get

```
romain@plume:~/temp/dktutorial$ dkcheck tut.dk 
[Warning] Invalid #NAME directive ignored.

[SUCCESS] File 'tut.dk' was successfully checked.
romain@plume:~/temp/dktutorial$ 

```

Cheers

**Comment by francoisthire** [comment]
Yes, we completely forgot to update the manual, sorry for that. 

We have decided to remove this directive so that the name of a module should be given by the basename of the file.

**Comment by rprimet** [comment]
Ah, there is a requirement that the name be the filename without extension?

**Comment by rprimet** [comment]
OK thanks for your reply!

**Comment by francoisthire** [comment]
Tutorial is not hosted on this repository. I close the issue.
