### ISSUE TITLE
Explicit error message for non-existent files?

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Dedukti#167]
As of now `dkcheck` fails silently (albeit thankfully with a nonzero error code) when a file does not exist.

```
romain@plume:~$ dkcheck nonexistent.dk
romain@plume:~$ 

```
It might be useful to output an explicit error message (at least when not running in quiet mode) to help debugging?

**Comment by francoisthire** [comment]
Yes, I noticed that. We will fix this for the next release.
