### ISSUE TITLE
Include filename in dkcheck error messages

### ISSUE THREAD

**Issue by rprimet** [Deducteam/Dedukti#168]
It might be helpful to echo the current filename when `dkcheck` emits an error. This is not completely necessary as the command line may give a clue in many instances, but it would make error sources more obvious and it seems that many compilers (e.g. gcc) and other tools that work on files do this by default.

```
romain@plume:~/inria/logipedia/Logipedia$ dkcheck library/fermat.dk
[ERROR:30] At line:2 column:2: Fail to open module 'sttfa'.

```

**Comment by francoisthire** [comment]
This will be in Dedukti 2.7 too.

**Comment by francoisthire** [comment]
In #125 , we fix this behavior by printing only the module name. For example:
```bash
~/Git/Dedukti/dkcheck.native tests/KO/brackets5.dk
```
we print

```dedukti
[ERROR:36] In module brackets5, at line:21 column:21: 
Error while reducing a term: a guard was not satisfied.
Found: brackets5.C.
Expected: brackets5.N
```

**Comment by rprimet** [comment]
LGTM!
