### ISSUE TITLE
Wrongly reported unsatisfiable constraints

### ISSUE THREAD

**Issue by GuillaumeGen** [Deducteam/Dedukti#183]
```
type : Type.
def Term : type -> Type.

Sigma : (A : type) -> (Term A -> type) -> Type.

pair : (A : type) -> (B : (Term A -> type)) -> (x : Term A) -> Term (B x) -> Sigma A (_ => B _).

def fst : (A : type) -> (B : (Term A -> type)) -> Sigma A (_ => B _) -> Term A.
[B,B',x] fst _ B (pair _ B' x _) --> x.
```
This file type-checks with the message 
```[Warning] At line:9 column:9: unsatisfiable constraint: B'[3] _[0] ~ B[5] _[0] (under 1 abstractions)```
Which is clearly wrong, since `B~B'` is a solution to this problem.

**Comment by GuillaumeGen** [comment]
The more interesting question is "are `B` and `B'` necessarily convertible?"
This would be required to type-checks the second projection of the dependent pair.

**Comment by fblanqui** [comment]
The following file is checked in LP:
```
symbol Type : TYPE
symbol Term : Type ⇒ TYPE
symbol prod : ∀A, (Term A ⇒ Type) ⇒ Type

rule Term (prod &A &B) → ∀x:Term &A, Term (&B x)

symbol const Sigma : ∀A, (Term A ⇒ Type) ⇒ TYPE
symbol pair : ∀A, ∀B, ∀x, Term (B x) ⇒ Sigma A B
symbol fst : ∀A, ∀B, Sigma A B ⇒ Term A

rule fst _ _ (pair _ _ &x _) → &x
```
Note that Sigma needs to be declared as constant (or injective).

The rule is fst A B (pair A' B' x y) --> x. x has type TA'. The LHS has type TA if SA'B'=SAB since pair A' B' x y has type SA'B'. Since S is injective, A'=A. Hence, TA'=TA.

**Comment by fblanqui** [comment]
By the way, there is something strange in DK. What is the meaning of (_ => B _)? This raises a parse error in LP. It works fine if it is replaced by B or (x => B x). It fails if it is replaced by (x => B _).

**Comment by GuillaumeGen** [comment]
Since `prod` was useless in this example, I suppressed it for minimality.

**Comment by GuillaumeGen** [comment]
Your example is also accepted in Dedukti 2, since the wrongly reported unsatisfiable constraint is linked to the eta-expansion.

**Comment by GuillaumeGen** [comment]
Concerning `(_ => B _)`, I don't know if it is a bug or a feature, but in places where it is unambiguous (ie everywhere but in the lhs of rewriting rules), `_`is an identifier like the others.

**Comment by fblanqui** [comment]
I don't understand your previous comment. Could you elaborate please?

**Comment by GuillaumeGen** [comment]
Which one?

**Comment by fblanqui** [comment]
https://github.com/Deducteam/Dedukti/issues/183#issuecomment-517240966

**Comment by GuillaumeGen** [comment]
The constraint elaborated by Dedukti is `B'[3] _[0] ~ B[5] _[0] (under 1 abstractions)` which is wrongly reported as unsatisfiable. If you don't eta-expand in types, the constraint become `B'[2] ~ B[4] (under 0 abstractions)` and Dedukti is easily able to see that this one is solvable (and even to transform it into a substitution.
This issue is in fact a double one.
 - This warning is clearly wrong. It should not be raised. This can be considered as a minor bug.
 - Is it safe when having the constraint  `B'[3] _[0] ~ B[5] _[0] (under 1 abstractions)` to elaborate the substitution `B'[2] --> B[4]`?

**Comment by fblanqui** [comment]
But, as explained in my first comment, you don't need to look at B or B' to check SR...

**Comment by GuillaumeGen** [comment]
Of course, the first point does not request any further discussion and is very easy to correct. But just suppress the warning is not very satisfactory.
Is it safe to transform a convertibility constraint of the form `X[n] _[ki] ... _[k0] ~ t (under m abstractions)` in `X[n-m] --> _ => ... => _ => t\sigma` where `\sigma` is the substitution `{k0->0, ..., ki -> i, j -> j-m if j >=m}` if  `_[k0] ... _[ki]` are distinct bound variables and`t` does not contain bound variable other than `_[k0] ... _[ki]`?

**Comment by GuillaumeGen** [comment]
> But, as explained in my first comment, you don't need to look at B or B' to check SR...

Indeed, but Dedukti 2 first infers a type and some constraints on the lhs, then transform the constraints in a substitution and finally type-checks the substituted rhs.
Constraints are inferred and resolved independently of the rhs.

**Comment by fblanqui** [comment]
This is a mistake. Contraints of the LHS do not need to be solved to check SR. But they may be useful to check the type of the RHS. We do it the right way in LP I think.

**Comment by fblanqui** [comment]
It would be clearer to formulate your question without using de Bruijn indices! ;-)

**Comment by GuillaumeGen** [comment]
Without de Bruijn indices, it becomes:
Is it safe to transform a convertibility constraint of the form `X xi ... x0 ~ t (under m abstractions)` in `X --> xi => ... => x0 => t` if  `x0 ... xi` are distinct bound variables and`t` does not contain bound variable other than `x0 ... xi`?

**Comment by fblanqui** [comment]
Well, x0 .. xi are free variables in fact. It looks safe if you do unification modulo eta, and X does not depend on x0 .. xi, that is, no solution for X can depend on x0 .. xi.

**Comment by GuillaumeGen** [comment]
> Well, x0 .. xi are free variables in fact.

I am not sure of what you mean by it. What I meant by "bound variables" was that they are not variables we perform matching on, contrarily to `X`.

> X does not depend on x0 .. xi, that is, no solution for X can depend on x0 .. xi.

Isn't that the meaning of bound?

**Comment by GuillaumeGen** [comment]
> This is a mistake. Contraints of the LHS do not need to be solved to check SR. But they may be useful to check the type of the RHS. We do it the right way in LP I think.

I thought (before Jui-Hsuan internship) the approach of LambdaPi was the same.

**Comment by fblanqui** [comment]
I don't think that you need all the free variables of t to be in x0..xi. You could have other free variables.

**Comment by rlepigre** [comment]
> Concerning `(_ => B _)`, I don't know if it is a bug or a feature, but in places where it is unambiguous (ie everywhere but in the lhs of rewriting rules), `_`is an identifier like the others.

That seems very wrong! It is definitely a bug.

**Comment by fblanqui** [comment]
Well, the point is that there is no metavariables in DK. So, (_ => B _) is alpha-equivalent to (x => B x) in DK. So, this is indeed correct. The point is that _ has a special meaning in LP. At the place of a binding variable like in [λ_,...] or in [∀_,...], it means a variable that cannot be bound. Every where else, it is syntactic sugar for a fresh metavariable applied to all the (explicit) variables in context. So, in LP, (_ => B _) is understood as (y => B M[A,B,x]), and (y => B _) as (y => B M[A,B,x,y]).

**Comment by fblanqui** [comment]
I agree with Rodolphe that it doesn't look like a very good idea to consider `_` as a valid identifier, except in binding positions as explained just before. (In OCaml, no indentifier starting with `_` can be bound.)

**Comment by GuillaumeGen** [comment]
> Is it safe to transform a convertibility constraint of the form X x0 ... xi ~ t (under m abstractions) in X --> x0 => ... => xi => t if x0 ... xi are distinct bound variables andt does not contain bound variable other than x0 ... xi?

No, it is not, because if X x ~ Y x, it tells us that X and Y are extensionally equal, not that they are equal, as shown in the new test `KO/EtaInConstraints_MoreEta_183.dk`.

**Comment by francoisthire** [comment]
It seems fixed now.
