### ISSUE TITLE
Documentation online

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#196]
At the moment, the documentation of Dedukti is not online, at least the one of the API. GitHub has a feature called `gh-pages` : https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

The question is what should we do? Have a branch `gh-pages`, a `docs` folder? The problem of a `docs` folder is that we have to commit the generated files which is not a good practice...

**Comment by gabrielhdt** [comment]
It seems to be a better idea to create a `gh-pages` branch in which the doc files are versioned, and periodically merge `master` in `gh-pages`.

**Comment by francoisthire** [comment]
Fixed. However the solution is temporary.
