### ISSUE TITLE
Compatibility with OCaml

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#197]
Currently, we aim to be compatible with OCaml 4.03, but this version is getting old. What should be our policy?

**Comment by gabrielhdt** [comment]
It's a good question, usually, projects decide to "freeze" dependencies at one point.  You should at least be compatible with OCaml 4.07 (because dk3 uses earley which is not compatible (yet?) with Ocaml 4.08)

**Comment by XVilka** [comment]
See https://github.com/Deducteam/Dedukti/pull/205
