### ISSUE TITLE
make fails with "cannot find z3"

### ISSUE THREAD

**Issue by 01mf02** [Deducteam/Dedukti#232]
~~~
$ make
File "universo/solving/dune", line 4, characters 40-42:
4 |         (libraries dedukti.api checking z3)
                                            ^^
Error: Library "z3" not found.
Hint: try: dune external-lib-deps --missing @@default
make: *** [GNUmakefile:18: bin] Error 1
~~~

Since the integration of Universo, the README is outdated. It should probably mention that either
(a) one can avoid installing z3 if running something like `make dkcheck.native`, or
(b) make explicit that z3 is required, and which version of it.

**Comment by francoisthire** [comment]
I have made this dependency explicit in 86032945 but this a temporary fix. `z3` should be optional.
