### ISSUE TITLE
Why dedukti forbid spaces and newlines in sident's ?

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/Dedukti#256]
https://github.com/Deducteam/Dedukti/blob/c65e7e66fe4bb8285db1856b8fe2a2532da2bd50/parsing/lexer.mll#L100-L103

**Comment by GuillaumeGen** [comment]
Is it really a feature to allow new line in identifier. Is there any example (in a programming language or proof assistant) where it is allowed / useful?
I am afraid that it will only lead to situation where
```
{| blablabla and I forget to close this identifier
Then a lot of clever things that were supposed to be a proof.
{| another (or the same) identifier |}
```
And all this just became a huge valid identifier, whereas it is completely unintended.

**Comment by GuillaumeGen** [comment]
#263 Allows spaces in file names and in identifiers, but new lines remain forbidden.
