### ISSUE TITLE
Confusing error messages when using extra parentheses

### ISSUE THREAD

**Issue by fblanqui** [Deducteam/Dedukti#259]
```
Set : Type.
Prop : Type.
def El : (Set -> Type).
def Prf : (Prop -> Type).
o : Set.
[] El o --> Prop.
forall : (x : Set -> (((El x) -> (El o)) -> Prop)).
[v0_X, v1_P] Prf ((forall (v0_X)) (v1_P)) --> (x : (El v0_X) -> (Prf (v1_P x))).
```
fails with:
```
[ERROR CODE:702]  [tmp/stack.dk] [line:8 column:34] 
Parsing error: Unexpected token '('.
```
When we remove the parentheses around v1_P we get a strange error message:
```
[ERROR CODE:702]  [tmp/stack.dk] [line:8 column:34] 
Parsing error: Unexpected token 'v1_P'.
```
It however works if we remove the parentheses around `forall (v0_X)`.

**Comment by GuillaumeGen** [comment]
Is the issue that you would like useless parentheses to be allowed in pattern? Or that you would like the error message to be more informative?
Both options seem very easy to achieve.

**Comment by fblanqui** [comment]
I guess that allowing useless parentheses would be the most natural but I would be fine with the other solution as well, although it is usually difficult to give good error messages. But this is not something very important for me now that I know what was the problem.
