### ISSUE TITLE
"Package conflict" when installing

### ISSUE THREAD

**Issue by yoni206** [Deducteam/Dedukti#311]
Hi,

I am trying to install `Deducti`. I first ran `opam install dedukti`, but then saw that it is outdated, and ran `opam uninstall dedukti`. Now I am trying to do `opam install . --deps-only` from the main directory of the repo, and am getting the following error:

```
$ opam install . --deps-only
[universo.~dev] synchronised (no changes)
[dedukti.2.6.0] synchronised (no changes)
[ERROR] Package conflict!
  * Missing dependency:
    - dedukti >= 2.7
    not available because the package is pinned to version 2.6.0

No solution found, exiting
```

Notice that `dedukti` does not occur in `opam list`.

Any solution for this?

**Comment by francoisthire** [comment]
The log you shown has the following line: `not available because the package is pinned to version 2.6.0`. Maybe you should consider to `unpin` Deduti first before installing Dedukti via the official repository?

**Comment by yoni206** [comment]
Yes, that worked! Thanks!
