### ISSUE TITLE
Links seem to 404

### ISSUE THREAD

**Issue by ice1000** [Deducteam/Dedukti#314]
![image](https://github.com/Deducteam/Dedukti/assets/16398479/264b23a4-8e75-4ac4-a268-7a576db53e4d)

http://www.lsv.fr/~dowek/Publi/expressing.pdf

**Comment by fblanqui** [comment]
Hi. This is an old draft that has never been published. It is better to refer to https://doi.org/10.46298/lmcs-19(1:12)2023 now. Best regards, Frédéric Blanqui.

**Comment by ice1000** [comment]
Appreciated!
