### ISSUE TITLE
Update the manual of the stable version

### ISSUE THREAD

**Issue by rafoo** [Deducteam/Dedukti#32]
The website contains a link to "the manual for the current version (v2.5) of Dedukti" pointing to https://github.com/Deducteam/Dedukti/blob/master/README.md. However, this is not the manual for the v2.5 version anymore but the development version. In particular, it contains instructions for opam pinning which are relevant to developers but not necesseraly to regular users and it does not contain instructions to install Dedukti from Deducteam's opam repository.

Moreover, the current stable version is v2.5.1, not v2.5. I think the manual has not yet been updated with the new syntactic construct (named rewrite-rule).

The manual for v2.5 is here: https://github.com/Deducteam/Dedukti/blob/a2618ac914c74b815c1a45519bda3a4b1cf743eb/README.md but it should probably contain instructions to get the v2.5 version instead of the master branch.

In my opinion, even the Readme of the devel version of Dedukti should target regular users, if we have things to tell to developers, we can put them in another file say Readme_for_devs.md.

**Comment by fblanqui** [comment]
Le 09/02/2018 à 15:57, Raphaël Cauderlier a écrit :
>
> In my opinion, even the Readme of the devel version of Dedukti should 
> target regular users, if we have things to tell to developers, we can 
> put them in another file say Readme_for_devs.md.
>
>
I agree. README should be for users. README.devel for developers.

**Comment by francoisthire** [comment]
This problem still exists for the version 2.6. Maybe one should write a document that explains what should be done for a new release?

**Comment by francoisthire** [comment]
Done in a6f25725
