### ISSUE TITLE
Module Basic is exported twice

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#41]
Error given by OCamlbuild on my project:

```
Error: Files /home/fthire/.opam/4.04.2/lib/dedukti/parser.cmxa
       and /home/fthire/.opam/4.04.2/lib/dedukti/kernel.cmxa
       both define a module named Basic
```

This error probably extends to all the modules defined by the kernel.

**Comment by rlepigre** [comment]
On my side, everything seems to work. Note that you can check the contents of a `cma` or `cmxa` with the `ocamlobjinfo` command. The module implementations contained in `parser` and `kernel` are the expected ones.
