### ISSUE TITLE
Function print_entry is missing

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#42]
Now that we have an entry type, probably we should add a function `print_entry` in the module `Pp`. This probably makes dkindent a bit useless because it will just call this function. Maybe it would be interesting that dkindent becomes an option for dkcheck? 

This would be very similar to the option --beautify of Coq.

**Comment by francoisthire** [comment]
Since the type `entry` is declared in `parser/parser.ml`, we cannot simply add a function print_entry in the module `Pp`. 

Either the `entry` type should be declared inside the kernel, otherwise the function `print_entry` should be exported by the `parser` module.

**Comment by rlepigre** [comment]
I think it would be fine to define it in the kernel.
