### ISSUE TITLE
WHNF definition

### ISSUE THREAD

**Issue by GuillaumeGen** [Deducteam/Dedukti#54]
The following example:
```
A : Type.

def g : A -> A.
def f : A -> A -> A.

def a : A.
def b : A.

[] g a --> f a b.
[] a --> b.
[x] f x x --> g x.

#EVAL[WHNF] (f a b).
```
returns `g a`.
What happens, is that Dedukti detects that `g` uses its first argument, calculates the WHNF of `a`, it is `b` and since `g b`does not match any head rewrite rule, Dedukti throws the reduct of the argument away and prints that `g a` is a WHNF.
It is really frustrating, since there is a rule which can be applied on the head of such a term.
But, there is a way to perform reductions from `g a` to a normal form with no step at the head, that's the reason why Dedukti calls it Weak Head Normal Form.

**Comment by rlepigre** [comment]
In my implementation, this returns `g b`, which makes a lot more sense. My intuition about these things tells me that matching a pattern should not trigger reductions. It actually does in my implementation, but in a way that is equivalent to first reducing, and then matching.

**Comment by rafoo** [comment]
I think that (part of) the paradoxical nature of your example comes from the fact that the pattern `g a` of your first rule is not in normal form.
