### ISSUE TITLE
Arity constraint for bound variables at the same position in patterns

### ISSUE THREAD

**Issue by Gaspi** [Deducteam/Dedukti#71]
In the following (non confluent) example, the two rules for `f` are forbidden because the locally bound variable `x` is used at the same position with different arities.

The reason for this constraint is unclear.
```
A : Type.
a : A.
b : A.

def T : A -> Type.
[] T a --> A -> A.
[] T _ --> (A -> A) -> A.

def f : x : A -> T x -> A.
[] f a (x => x  ) --> a.
[] f _ (x => x a) --> a.
```

**Comment by fblanqui** [comment]
Le 16/04/2018 à 15:58, Gaspard Férey a écrit :
>
> In the following (non confluent) example, the two rules for |f| are 
> forbidden because the locally bound variable |x| is used at the same 
> position with different arities.
>
> The reason for this constraint is unclear.
>
> |A : Type. a : A. b : A. def T : A -> Type. [] T a --> A -> A. [] T _ 
> --> (A -> A) -> A. def f : x : A -> T x -> A. [] f a (x => x ) --> a.|
|This rule should clearly be accepted, whatever the structure of the LHS is.

|
> |[] f _ (x => x a) --> a. |
>
Idem, because, whatever the structure of the LHS is, if it is typable, 
then it is of type A, as the RHS.

What happens if you replace _ by b in all the rules?

**Comment by francoisthire** [comment]
It works now.
