### ISSUE TITLE
WHNF and confluence

### ISSUE THREAD

**Issue by francoisthire** [Deducteam/Dedukti#89]
On the example below, we observe a strange behavior:

```
A : Type.

a : A.

aa : A -> A.

def f : (A -> A) -> A -> A.

def g : (A -> A) -> A -> A.

def h : (A -> A) -> (A -> A) -> A -> A.

def bb : A -> A := aa.

(; WHNF not well-defined on non confluent system ;)
[] f (x => bb x) --> (x : A => aa x).

#EVAL[WHNF] f (x => bb x).
```

Dedukti gives us that the WHNF of `f (x => bb x)` is itself while it is obviously a redex. The reason is that `bb` being defined, Dedukti tries first to reduce the argument (x => bb x) (not using a WHNF strategy), that reduces to (x => aa x), and then tries to match the pattern.

I think the manual should clearly state that the WHNF strategy is not well-defined for non-confluent systems. Notice that this behavior applies also to the HNF strategy.

**Comment by rlepigre** [comment]
Well, dedukti itself is not well-defined on non-confluent systems!

**Comment by francoisthire** [comment]
Well, I am talking of the rewriting engine instead of the type checker.

Le mar. 19 juin 2018 à 11:54, Rodolphe Lepigre <notifications@github.com> a
écrit :

**Comment by GuillaumeGen** [comment]
See #90 for a definition of WHNF as implemented now by Dedukti (is it a good definition is still an open problem).

**Comment by francoisthire** [comment]
I have the impression that my example contradicts your definition. You should had the hypothesis that the rewrite system is confluent.

**Comment by GuillaumeGen** [comment]
Why ?
`f (x => bb x)` reduces to `f (x => aa x)`, which is in normal form and no reduction occurs at the head.
