### ISSUE TITLE
Install the sublibs in distinct directories

### ISSUE THREAD

**Issue by rafoo** [Deducteam/Dedukti#93]
Hello,

I am trying to use the `dedukti.kernel` sublib to build a v2.6.0 version of Sukerujo.

Currently, the `dedukti` library as well as its two sublibs `dedukti.kernel` and `dedukti.parser` are all installed in the same directory (typically `~/.opam/<switch>/lib/dedukti`). As a result, it is not possible to add one of the sublibs to OCaml's path without also adding the other one.

As a result, when compiling Sukerujo, I get the following warning from ocamlfind:

`findlib: [WARNING] Interface parser.cmi occurs in several directories: parser, /home/cauderlier/.opam/4.05.0+flambda/lib/dedukti`.

On IRC (channel #deducteam on irc.freenode.net), @c-cube has suggested a solution based on jbuilder. His nunchaku project (https://github.com/nunchaku-inria/nunchaku) uses this solution.

**Comment by c-cube** [comment]
I'll just say that jbuilder/dune is really simple to use for this kind of project (multiple sub-libraries). The nunchaku repo shows how to do it. I'd be happy to help if using jbuilder is something that interests Dedukti's maintainers.

**Comment by francoisthire** [comment]
@Gaspi any opinion? I am not against using jbuilder/dune.
